export type EventErrorCode =
  | 'EVENT_TITLE_INVALID'
  | 'EVENT_DESCRIPTION_TOO_SHORT'
  | 'EVENT_CATEGORY_INVALID'
  | 'EVENT_PHOTO_COUNT_INVALID'
  | 'EVENT_REJECTION_REASON_REQUIRED'
  | 'EVENT_PHOTO_NOT_FOUND'
  | 'EVENT_MEDIA_KEY_REQUIRED'
  | 'EVENT_MEDIA_NOT_READY'
  | 'EVENT_NOT_READY'
  | 'EVENT_ALREADY_PUBLISHED'
  | 'EVENT_START_DATE_INVALID'
  | 'EVENT_START_DATE_NOT_FUTURE'
  | 'EVENT_END_DATE_INVALID'
  | 'EVENT_END_DATE_NOT_AFTER_START'
  | 'EVENT_LATITUDE_INVALID'
  | 'EVENT_LONGITUDE_INVALID'
  | 'EVENT_PRICE_NOT_ALLOWED'
  | 'EVENT_FIXED_PRICE_INVALID'
  | 'EVENT_FIXED_PRICE_MAX_NOT_ALLOWED'
  | 'EVENT_PRICE_RANGE_REQUIRED'
  | 'EVENT_PRICE_RANGE_INVALID'
  | 'EVENT_PRICE_TYPE_INVALID';

export class DomainValidationError extends Error {
  constructor(public readonly code: EventErrorCode) {
    super(code);
    this.name = 'DomainValidationError';
  }
}
